#!/bin/bash

# Colores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE} Installing Python DNS...${NC}"

# 1. Python adn Git installation
sudo apt-get update > /dev/null 2>&1
sudo apt-get install python3 python3-venv python3-pip git -y > /dev/null 2>&1

# 2. Clone repository
TARGET_DIR="/opt/pihole-dns-manager"
sudo mkdir -p $TARGET_DIR
sudo chown $USER:$USER $TARGET_DIR

echo -e "${BLUE} Cloning repository...${NC}"
if [ -d "$TARGET_DIR/.git" ]; then
    cd $TARGET_DIR && git pull > /dev/null 2>&1
else
    git clone https://codeberg.org/ben/pihole_dns.git $TARGET_DIR > /dev/null 2>&1
fi

# 3. Create virtual enviroment
cd $TARGET_DIR
echo -e "${BLUE} Creating Python Virtual Environment...${NC}"
python3 -m venv venv
source venv/bin/activate

# 4. Installing depencies
echo -e "${BLUE} Installing Python requirements...${NC}"
pip install requests > /dev/null 2>&1

# 5. Script
 echo -e "${BLUE}🚀 Creating launcher script...${NC}"
    cat <<EOF > $TARGET_DIR/run_dns_sync.sh
#!/bin/bash
export PIHOLE_URL="http://127.0.0.1"
export PIHOLE_PASSWORD="$GENERATED_PASS"

echo "Running DNS Manager..."
cd $TARGET_DIR
source venv/bin/activate
python3 pihole_dns.py "\$@"
EOF
    
    chmod +x $TARGET_DIR/run_dns_sync.sh


echo -e "${GREEN} Python DNS installed at: $TARGET_DIR${NC}"
echo -e "   Usage: ./run_dns_sync.sh"
